version: '3.1'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create-postgres-db.sql:/docker-entrypoint-initdb.d/create-postgres-db.sql

volumes:
  mongodb_data:
  postgres_data:
