name: Build and Deploy

on:
  push:
    branches:
      - main
      - testCI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Build Docker image
      run: docker build -t ilyes/web_project:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ilyesefrei
        password: ilyesefrei
        
    - name: Push to Docker Hub
      run: |
        docker push ilyesefrei/web_project:tagname