name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Go to BackEnd
      run: cd back
      
    - name: Print Working Directory
      run: pwd

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Build Docker image
      run: docker build -t ilyesefrei/web_project:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - name: Push to Docker Hub
      run: |
        docker push ilyesefrei/web_project:latest

    - name: Trigger Render Deployment
      run: curl -X POST https://api.render.com/deploy/srv-cpg2bimct0pc73d5ieng?key=fW56L5bFRCE