name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Set up environment variables
      run: echo "DATABASE_PORT=5432" >> $GITHUB_ENV
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set up environment variables
      run: echo "DATABASE_PORT=5432" >> $GITHUB_ENV

    - name: Set up Docker Compose
      run: |
        cd back
        docker-compose up -d

    - name: Wait for services to be ready
      run: sleep 30

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ilyesefrei/web_project:latest

    - name: Trigger Render Deployment
      run: curl -X POST https://api.render.com/deploy/srv-cpg2bimct0pc73d5ieng?key=fW56L5bFRCE
