name: Build and Deploy

on:
  push:
    branches:
      - main
      - testCI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Build to Docker Hub
      run: docker build -t ghcr.io/ilyesb36/web_project:latest .

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.SECRET_TOKEN }}
        
    - name: Push to GitHub Container Registry
      run: |
        docker push ghcr.io/ilyesb36/web_project:latest