name: Build and Deploy

on:
  push:
    branches:
      - main
      - testCI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Build to Docker Hub
      run: |
        docker build -t web_project .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: 'ilyesb36'
        password: ${{ secrets.SECRET_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: user/mywebapp:latest