name: Build and Deploy

on:
  push:
    branches:
      - main
      - testCI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Build Docker image
      run: docker build -t ilyesefrei/web_project:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - name: Push to Docker Hub
      run: |
        docker push ilyesefrei/web_project:latest

    # - name: Install Heroku CLI
    #   run: curl https://cli-assets.heroku.com/install.sh | sh

    # - name: Login to Heroku
    #   run: heroku container:login
    #   env:
    #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    # - name: Push to Heroku
    #   run: heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}

    # - name: Release to Heroku
    #   run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}